name = "scope3-segments-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
API_TIMEOUT = "200"
CACHE_TTL = "3600"

# Development environment with higher timeouts
[env.development]
name = "scope3-segments-worker-dev"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[env.development.vars]
API_TIMEOUT = "5000"
CACHE_TTL = "3600"

# Using Cache API instead of KV for development environment

# Route handler test environment
[env.routes]
name = "scope3-segments-worker-routes"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[env.routes.vars]
API_TIMEOUT = "2000"
CACHE_TTL = "3600"

# Using Cache API instead of KV for routes environment

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[placement]
mode = "smart"
