name = "scope3-segments-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for segments caching
[[kv_namespaces]]
binding = "SEGMENTS_CACHE"
id = "ba6f9832bf864df7bf030abe1bf53988"

# Environment variables
[vars]
API_TIMEOUT = "200"
CACHE_TTL = "3600"

# Secret environment variables - set these with:
# npx wrangler secret put SCOPE3_API_KEY
# Note: Secrets are configured in Cloudflare dashboard or via wrangler commands
# Do not include the [secrets] section in wrangler.toml as it's not officially supported

# Development environment with higher timeouts
[env.development]
name = "scope3-segments-worker-dev"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[env.development.vars]
API_TIMEOUT = "5000"
CACHE_TTL = "3600"

# Copy KV namespaces to development environment
[[env.development.kv_namespaces]]
binding = "SEGMENTS_CACHE"
id = "ba6f9832bf864df7bf030abe1bf53988"

# Route handler test environment
[env.routes]
name = "scope3-segments-worker-routes"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[env.routes.vars]
API_TIMEOUT = "2000"
CACHE_TTL = "3600"

# Copy KV namespaces to routes environment
[[env.routes.kv_namespaces]]
binding = "SEGMENTS_CACHE"
id = "ba6f9832bf864df7bf030abe1bf53988"

# Routes configuration
[env.routes.routes]
pattern = "example.com/*"
zone_name = "example.com"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
